import {
  Swords,
  Zap,
  Calendar,
  Users,
  List,
  AreaChart,
  BarChart3,
  TrendingUp,
  Star,
  LayoutGrid,
  Sparkles,
  Navigation,
} from "lucide-react";
import type { DashboardWidgetDefinition } from "@/types/dashboard";

export const DASHBOARD_WIDGET_REGISTRY: DashboardWidgetDefinition[] = [
  // Team widgets
  {
    id: "matchup-score",
    name: "Matchup Score",
    description: "Live score vs opponent with projected margin",
    icon: Swords,
    category: "team",
    defaultW: 4,
    defaultH: 4,
    minW: 3,
    minH: 3,
    requiresTeam: true,
  },
  {
    id: "roster-overview",
    name: "Roster Overview",
    description: "Full roster with avg FPTS, trends, and injury badges",
    icon: List,
    category: "team",
    defaultW: 4,
    defaultH: 6,
    minW: 3,
    minH: 4,
    requiresTeam: true,
  },
  {
    id: "daily-breakdown",
    name: "Daily Breakdown",
    description: "Day-by-day matchup grid with live scores",
    icon: LayoutGrid,
    category: "team",
    defaultW: 4,
    defaultH: 4,
    minW: 3,
    minH: 3,
    requiresTeam: true,
  },
  {
    id: "score-history",
    name: "Score History",
    description: "Matchup score chart across the current period",
    icon: AreaChart,
    category: "team",
    defaultW: 4,
    defaultH: 4,
    minW: 3,
    minH: 3,
    requiresTeam: true,
  },
  {
    id: "category-strengths",
    name: "Category Strengths",
    description: "Your team vs opponent category comparison bars",
    icon: BarChart3,
    category: "team",
    defaultW: 3,
    defaultH: 4,
    minW: 3,
    minH: 3,
    requiresTeam: true,
  },
  {
    id: "team-streamers",
    name: "Team Streamers",
    description: "Streaming pickups for your team's weaknesses",
    icon: Sparkles,
    category: "team",
    defaultW: 3,
    defaultH: 5,
    minW: 2,
    minH: 4,
    requiresTeam: true,
  },
  // Market widgets
  {
    id: "streamers",
    name: "Streamers",
    description: "Breakout pickup candidates from injury opportunities",
    icon: Zap,
    category: "market",
    defaultW: 3,
    defaultH: 5,
    minW: 2,
    minH: 4,
    requiresTeam: false,
  },
  {
    id: "today-leaders",
    name: "Today's Leaders",
    description: "Live fantasy point leaderboard for today's games",
    icon: Users,
    category: "market",
    defaultW: 4,
    defaultH: 5,
    minW: 3,
    minH: 4,
    requiresTeam: false,
  },
  {
    id: "trending",
    name: "Trending Players",
    description: "Players with rising/falling ownership percentages",
    icon: TrendingUp,
    category: "market",
    defaultW: 3,
    defaultH: 4,
    minW: 2,
    minH: 3,
    requiresTeam: false,
  },
  // Schedule widgets
  {
    id: "schedule",
    name: "Today's Games",
    description: "NBA schedule with live scores and game status",
    icon: Calendar,
    category: "schedule",
    defaultW: 3,
    defaultH: 5,
    minW: 2,
    minH: 4,
    requiresTeam: false,
  },
  // Utility widgets
  {
    id: "watchlist",
    name: "Watchlist",
    description: "Your saved player watch list",
    icon: Star,
    category: "utility",
    defaultW: 3,
    defaultH: 4,
    minW: 2,
    minH: 3,
    requiresTeam: false,
  },
  {
    id: "quick-actions",
    name: "Quick Actions",
    description: "Shortcuts to Terminal, Rankings, Matchup, and more",
    icon: Navigation,
    category: "utility",
    defaultW: 2,
    defaultH: 2,
    minW: 2,
    minH: 2,
    requiresTeam: false,
  },
];

export function getWidgetDefinition(
  id: string
): DashboardWidgetDefinition | undefined {
  return DASHBOARD_WIDGET_REGISTRY.find((w) => w.id === id);
}
